name: ✨ 기능 추가
description: Project에 새로운 기능을 추가할 때 사용하세요.
title: "[FEAT] "
labels: ["feature"]
body:
  - type: input
    id: summary
    attributes:
      label: 기능 요약
      placeholder: 예) 팀원 조회
    validations:
      required: true
  - type: textarea
    id: detail
    attributes:
      label: 상세 설명
      description: 어떤 흐름으로 동작해야 하는지 적어주세요.
  
